/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora;

import static java.lang.Math.sqrt;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class calculadora extends javax.swing.JFrame {

    private String cadenaNumeros="";
    private double numero, resultado=0;
    private String operacion="nula";
    private boolean activado=true,punto=true;
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void botonIgual(){
        double numero2;
        if(operacion=="nula"){
            etiquetaES.setText(cadenaNumeros);
        }
        else if(operacion=="suma"){
            numero2= Double.parseDouble(cadenaNumeros);
            resultado= numero + numero2;         
            etiquetaES.setText(String.format("%.2f" , resultado));
            cadenaNumeros= String.valueOf(resultado);
            operacion="nula";         
        }
        else if(operacion=="resta"){
            numero2= Double.parseDouble(cadenaNumeros);
            resultado= numero - numero2;          
            etiquetaES.setText(String.format("%.2f" , resultado));
            cadenaNumeros= String.valueOf(resultado);
            operacion="nula";
        }
        else if(operacion=="division"){
            numero2= Double.parseDouble(cadenaNumeros);
            resultado= numero / numero2;        
            etiquetaES.setText(String.format("%.2f" , resultado));
            cadenaNumeros= String.valueOf(resultado);
            operacion="nula";
        }
        else if(operacion=="multiplicacion"){
            numero2= Double.parseDouble(cadenaNumeros);
            resultado= numero * numero2;          
            etiquetaES.setText(String.format("%.2f" , resultado));//Solo mostrar dos decimales
            cadenaNumeros= String.valueOf(resultado);//Obtener un string de un double
            operacion="nula";
        }
        
        etiquetaHistorial.setText("");  
        activado=true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPantalla = new javax.swing.JPanel();
        etiquetaHistorial = new javax.swing.JLabel();
        etiquetaES = new javax.swing.JLabel();
        panelNumeros = new javax.swing.JPanel();
        botonClear = new javax.swing.JButton();
        botonRaiz = new javax.swing.JButton();
        botonDivision = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonMultiplicacion = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonResta = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonSumar = new javax.swing.JButton();
        botonMasOMenos = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuUsos = new javax.swing.JMenu();
        itemCalculadora = new javax.swing.JMenuItem();
        itemDivisas = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        panelPantalla.setLayout(new java.awt.GridBagLayout());

        etiquetaHistorial.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        etiquetaHistorial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 20);
        panelPantalla.add(etiquetaHistorial, gridBagConstraints);

        etiquetaES.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        etiquetaES.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etiquetaES.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 20);
        panelPantalla.add(etiquetaES, gridBagConstraints);

        panelNumeros.setLayout(new java.awt.GridLayout(5, 4));

        botonClear.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonClear.setText("C");
        botonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClearActionPerformed(evt);
            }
        });
        panelNumeros.add(botonClear);

        botonRaiz.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonRaiz.setText("√");
        botonRaiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRaizActionPerformed(evt);
            }
        });
        panelNumeros.add(botonRaiz);

        botonDivision.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonDivision.setText("÷");
        botonDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDivisionActionPerformed(evt);
            }
        });
        panelNumeros.add(botonDivision);

        botonBorrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/borrar.png"))); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        panelNumeros.add(botonBorrar);

        boton7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton7);

        boton8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton8);

        boton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton9);

        botonMultiplicacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonMultiplicacion.setText("X");
        botonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultiplicacionActionPerformed(evt);
            }
        });
        panelNumeros.add(botonMultiplicacion);

        boton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton4);

        boton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton5);

        boton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton6);

        botonResta.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonResta.setText("-");
        botonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestaActionPerformed(evt);
            }
        });
        panelNumeros.add(botonResta);

        boton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton1);

        boton2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton2);

        boton3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton3);

        botonSumar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonSumar.setText("+");
        botonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSumarActionPerformed(evt);
            }
        });
        panelNumeros.add(botonSumar);

        botonMasOMenos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonMasOMenos.setText("±");
        botonMasOMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasOMenosActionPerformed(evt);
            }
        });
        panelNumeros.add(botonMasOMenos);

        boton0.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        panelNumeros.add(boton0);

        botonPunto.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });
        panelNumeros.add(botonPunto);

        botonIgual.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        panelNumeros.add(botonIgual);

        menuUsos.setText("Usos");
        menuUsos.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        menuUsos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsosActionPerformed(evt);
            }
        });

        itemCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCalculadora.png"))); // NOI18N
        itemCalculadora.setText("Calculadora Estándar");
        menuUsos.add(itemCalculadora);

        itemDivisas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/divisa.png"))); // NOI18N
        itemDivisas.setText("Convertidor de divisas");
        itemDivisas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDivisasActionPerformed(evt);
            }
        });
        menuUsos.add(itemDivisas);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuUsos.add(itemSalir);

        jMenuBar1.add(menuUsos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNumeros, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        try{
            if(cadenaNumeros.charAt(cadenaNumeros.length()-1)=='.'){
            punto=true;
            }
            if(cadenaNumeros!=""){
                if(cadenaNumeros.length() == 1){
                    etiquetaES.setText("0");
                    cadenaNumeros= cadenaNumeros.substring(0, cadenaNumeros.length()-1);//Borrar el ultimo caracter de una cadena de texto
                    activado=false;
                }
                else{
                    cadenaNumeros= cadenaNumeros.substring(0, cadenaNumeros.length()-1);
                    etiquetaES.setText(cadenaNumeros);
                }           
            }
        } catch(StringIndexOutOfBoundsException si){
            
        }  
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void itemDivisasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDivisasActionPerformed
        convertidordeDivisas cd= new convertidordeDivisas();
        dispose();
        cd.setVisible(true);
        
    }//GEN-LAST:event_itemDivisasActionPerformed

    private void menuUsosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUsosActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        if(cadenaNumeros!=""){
            cadenaNumeros+="0";
            etiquetaES.setText(cadenaNumeros);
            activado=true;            
        }
    }//GEN-LAST:event_boton0ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        cadenaNumeros+="1";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
        cadenaNumeros+="2";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        cadenaNumeros+="3";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        cadenaNumeros+="4";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        cadenaNumeros+="5";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        cadenaNumeros+="6";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        cadenaNumeros+="7";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        cadenaNumeros+="8";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        cadenaNumeros+="9";
        etiquetaES.setText(cadenaNumeros);
        activado=true;
    }//GEN-LAST:event_boton9ActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        if(punto==true){
            if(cadenaNumeros==""){
                cadenaNumeros+="0.";
            }
            else{
                cadenaNumeros+=".";
            }
            etiquetaES.setText(cadenaNumeros);
        }

        punto=false;
        activado=true;
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumarActionPerformed
        
        try{
            if(etiquetaHistorial.getText()!=""){
                if(activado==true){
                    botonIgual();
                    operacion="suma";
                    numero= Double.parseDouble(cadenaNumeros);
                    etiquetaHistorial.setText(cadenaNumeros+" +");
                    cadenaNumeros="";
                    punto=true;
                    activado=false;
                } 
            }
            else{
                if(activado=true){
                operacion="suma";
                numero= Double.parseDouble(cadenaNumeros);
                etiquetaHistorial.setText(cadenaNumeros+" +");
                cadenaNumeros="";
                punto=true;
                activado=false;
                }
            }
           
        } catch (NumberFormatException nf){
            
        }
    }//GEN-LAST:event_botonSumarActionPerformed

    private void botonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestaActionPerformed
        
        try{
            if(etiquetaHistorial.getText()!=""){
                if(activado==true){
                    botonIgual();
                    operacion="resta";
                    numero= Double.parseDouble(cadenaNumeros);
                    etiquetaHistorial.setText(cadenaNumeros+" -");
                    cadenaNumeros="";
                    punto=true;
                    activado=false;
                } 
            }
            else{
                if(activado==true){
                operacion="resta";
                numero= Double.parseDouble(cadenaNumeros);
                etiquetaHistorial.setText(cadenaNumeros+" +");
                cadenaNumeros="";
                punto=true;
                activado=false;
                }
            }
        } catch (NumberFormatException nf){
            
        }
    }//GEN-LAST:event_botonRestaActionPerformed

    private void botonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMultiplicacionActionPerformed
        try{
           if(etiquetaHistorial.getText()!=""){
                if(activado==true){
                    botonIgual();
                    operacion="multiplicacion";
                    numero= Double.parseDouble(cadenaNumeros);
                    etiquetaHistorial.setText(cadenaNumeros+" x");
                    cadenaNumeros="";
                    punto=true;
                    activado=false;
                } 
            }
            else{
                if(activado==true){
                operacion="multiplicacion";
                numero= Double.parseDouble(cadenaNumeros);
                etiquetaHistorial.setText(cadenaNumeros+" x");
                cadenaNumeros="";
                punto=true;
                activado=false;
                }
            }
        } catch (NumberFormatException nf){
            
        }      
    }//GEN-LAST:event_botonMultiplicacionActionPerformed

    private void botonDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivisionActionPerformed
        try{
            if(etiquetaHistorial.getText()!=""){
                if(activado==true){
                    botonIgual();
                    operacion="division";
                    numero= Double.parseDouble(cadenaNumeros);
                    etiquetaHistorial.setText(cadenaNumeros+" ÷");
                    cadenaNumeros="";
                    punto=true;
                    activado=false;
                } 
            }
            else{
                if(activado==true){
                operacion="division";
                numero= Double.parseDouble(cadenaNumeros);
                etiquetaHistorial.setText(cadenaNumeros+" ÷");
                cadenaNumeros="";
                punto=true;
                activado=false;
                }
            }
        } catch (NumberFormatException nf){
            
        }  
    }//GEN-LAST:event_botonDivisionActionPerformed

    private void botonRaizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRaizActionPerformed
        try{
            if(activado==true && cadenaNumeros!=""){
            etiquetaHistorial.setText("sqrt("+cadenaNumeros+")");
            numero= Double.parseDouble(cadenaNumeros);
            resultado= sqrt(numero);
            etiquetaES.setText(String.format("%.2f" , resultado));
            cadenaNumeros= String.valueOf(resultado);
        }
        } catch (NumberFormatException nf){
            
        }  
    }//GEN-LAST:event_botonRaizActionPerformed

    private void botonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClearActionPerformed
        if(cadenaNumeros!=""){
            cadenaNumeros="";
            punto=true;
            activado=true;            
            etiquetaES.setText("0");
            etiquetaHistorial.setText("");
        }
    }//GEN-LAST:event_botonClearActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
        try{
            botonIgual();
        } catch(NumberFormatException nf){
            
        }
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonMasOMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMasOMenosActionPerformed
        if(cadenaNumeros.charAt(0) != '-'){
            cadenaNumeros= "-"+cadenaNumeros;
        }
        else{
            cadenaNumeros=cadenaNumeros.substring(1,cadenaNumeros.length());//Borrar el primer caracter de una cadena de texto
        }
        etiquetaES.setText(cadenaNumeros);
    }//GEN-LAST:event_botonMasOMenosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            UIManager.setLookAndFeel("com.jtattoo.plaf.luna.LunaLookAndFeel");
        } catch (ClassNotFoundException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
           // Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex)
        {
            //Logger.getLogger(Ventana.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonClear;
    private javax.swing.JButton botonDivision;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMasOMenos;
    private javax.swing.JButton botonMultiplicacion;
    private javax.swing.JButton botonPunto;
    private javax.swing.JButton botonRaiz;
    private javax.swing.JButton botonResta;
    private javax.swing.JButton botonSumar;
    private javax.swing.JLabel etiquetaES;
    private javax.swing.JLabel etiquetaHistorial;
    private javax.swing.JMenuItem itemCalculadora;
    private javax.swing.JMenuItem itemDivisas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuUsos;
    private javax.swing.JPanel panelNumeros;
    private javax.swing.JPanel panelPantalla;
    // End of variables declaration//GEN-END:variables
}
